sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - 0bsd

reviewed:
  npm:
  - sax
  - escodegen
  - estraverse
  - esutils
  - ieee754
  - readable-stream
  - source-map
  - string_decoder