name: Sync Upstream

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: fopina/upstream-to-pr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upstream-repository: https://github.com/actions/cache